-- Synthetic demo data for RolloMap (public README screenshots).
-- Everyone here is fictional. No real people. All emails @example.com.
-- Idempotent-friendly single DO block, workspace-scoped.

DO $$
DECLARE
  ws CONSTANT UUID := '00000000-0000-0000-0000-000000000001';
BEGIN
  ------------------------------------------------------------------
  -- People (~40)
  ------------------------------------------------------------------
  INSERT INTO person (workspace_id, display_name, primary_email, company, title, summary, how_known, first_seen_at, last_seen_at, interaction_count, relationship_strength, confidence)
  VALUES
    -- Hero profiles (rich below)
    (ws, 'Amara Osei', 'amara.osei@example.com', 'Loomwork', 'Founder & CEO',
     'Building autonomous agents for back-office operations. Sharp, fast-moving, always shipping.',
     'Met at the AI Engineer Summit, 2025.', '2024-11-03', '2026-06-28', 9, 0.88, 0.97),
    (ws, 'Diego Ramirez', 'diego.ramirez@example.com', 'Meridian Ventures', 'Partner',
     'Early-stage investor with a climate and hard-tech thesis. Generous with introductions.',
     'Introduced by a mutual founder friend in 2023.', '2023-04-15', '2026-06-10', 7, 0.82, 0.95),
    (ws, 'Sofia Lindqvist', 'sofia.lindqvist@example.com', 'Northwind', 'Head of Design',
     'Leads design systems at a growth-stage fintech. Deep craft, calm under pressure.',
     'Ex-colleague from agency days.', '2021-08-20', '2026-06-22', 11, 0.90, 0.98),
    (ws, 'Kenji Tanaka', 'kenji.tanaka@example.com', 'Rustforge', 'Staff Engineer',
     'Maintains a popular open-source build tool. Thoughtful about developer experience.',
     'Met through an open-source project I contributed to.', '2022-02-11', '2026-05-30', 8, 0.80, 0.96),
    (ws, 'Nadia Haddad', 'nadia.haddad@example.com', 'Assembly', 'Community Lead',
     'Runs one of the best operator communities I know. A connector to her core.',
     'Met at a community-builders dinner in 2024.', '2024-01-18', '2026-06-15', 10, 0.85, 0.97),
    -- Supporting network
    (ws, 'Marcus Bell', 'marcus.bell@example.com', 'Cadence Labs', 'CTO',
     'Infrastructure engineer building data pipelines. Dry sense of humor.',
     'Introduced over email by a former colleague.', '2023-09-01', '2026-03-12', 4, 0.55, 0.90),
    (ws, 'Yuki Sato', 'yuki.sato@example.com', 'Paperlane', 'Product Manager',
     'PM at a docs startup who cares a lot about user research.',
     'Met at a product meetup in Seattle.', '2024-05-22', '2026-04-02', 3, 0.40, 0.88),
    (ws, 'Olumide Adeyemi', 'olumide.adeyemi@example.com', 'GridPositive', 'Founder',
     'Climate founder working on grid-scale battery-dispatch software.',
     'Introduced by Diego Ramirez.', '2025-02-14', '2026-05-18', 5, 0.60, 0.92),
    (ws, 'Hannah Cohen', 'hannah.cohen@example.com', 'Brightseed', 'VP Engineering',
     'Scaling an engineering org from 20 to 80. Pragmatic, people-first leader.',
     'Met at a leadership offsite.', '2023-11-30', '2026-02-20', 4, 0.50, 0.90),
    (ws, 'Rafael Santos', 'rafael.santos@example.com', 'Tidepool Design', 'Principal Designer',
     'Freelance product designer covering brand and UI. Great taste.',
     'Worked together on a client project.', '2022-06-15', '2025-12-05', 3, 0.45, 0.87),
    (ws, 'Mei Chen', 'mei.chen@example.com', 'Fathom AI', 'ML Researcher',
     'Works on retrieval and evaluation for LLM systems.',
     'Met at a research reading group.', '2024-09-10', '2026-06-01', 4, 0.52, 0.90),
    (ws, 'Tomas Herrera', 'tomas.herrera@example.com', 'Solaria', 'Head of Growth',
     'Growth operator out of consumer apps. High energy.',
     'Met at SaaStr, 2024.', '2024-09-13', '2025-11-22', 2, 0.30, 0.85),
    (ws, 'Aisha Rahman', 'aisha.rahman@example.com', 'Kindred Health', 'Founder & CEO',
     'Building patient-navigation software for small clinics.',
     'Introduced by Nadia Haddad.', '2025-03-20', '2026-06-05', 4, 0.58, 0.91),
    (ws, 'Lars Nielsen', 'lars.nielsen@example.com', 'Fjord Capital', 'Principal',
     'Growth investor with a European fintech focus.',
     'Met at a fintech conference in London.', '2023-06-08', '2025-10-14', 2, 0.28, 0.84),
    (ws, 'Priyanka Nair', 'priyanka.nair@example.com', 'Loopback', 'Founding Engineer',
     'Full-stack engineer who loves developer tooling.',
     'Ex-colleague and good friend.', '2021-03-05', '2026-04-19', 6, 0.68, 0.94),
    (ws, 'Grace Okafor', 'grace.okafor@example.com', 'Verdant', 'Sustainability Lead',
     'Runs sustainability programs and wants to move into climate tech.',
     'Found me through her newsletter.', '2024-11-02', '2026-03-30', 3, 0.42, 0.88),
    (ws, 'Daniel Park', 'daniel.park@example.com', 'Stacks', 'Founder',
     'Solo founder building developer-productivity tools.',
     'Met in an indie-hackers Slack.', '2023-07-19', '2026-05-11', 5, 0.60, 0.90),
    (ws, 'Fatima Al-Sayed', 'fatima.alsayed@example.com', 'Horizon Foundation', 'Program Director',
     'Runs a grantmaking program for civic technology.',
     'Met at a nonprofit-tech convening.', '2022-10-25', '2025-09-08', 3, 0.38, 0.86),
    (ws, 'Ben Whitfield', 'ben.whitfield@example.com', 'Cobalt', 'Sales Director',
     'Enterprise sales leader. Warm and straight-talking.',
     'Worked a deal together.', '2023-02-28', '2025-12-19', 3, 0.40, 0.87),
    (ws, 'Ingrid Bergstrom', 'ingrid.bergstrom@example.com', 'Nimbus', 'Head of People',
     'People leader who is thoughtful about hiring and culture.',
     'Met at a people-ops roundtable.', '2024-04-11', '2026-04-25', 4, 0.50, 0.89),
    (ws, 'Carlos Mendoza', 'carlos.mendoza@example.com', 'Adobe', 'Senior Product Manager',
     'Big-company PM with a persistent startup itch.',
     'Old friend from grad school.', '2021-01-15', '2026-01-30', 5, 0.62, 0.92),
    (ws, 'Zoe Armstrong', 'zoe.armstrong@example.com', 'Wildcard', 'Creative Director',
     'Brand and campaign work for technology companies.',
     'Met at a design conference.', '2023-05-17', '2025-11-09', 2, 0.32, 0.85),
    (ws, 'Omar Farouk', 'omar.farouk@example.com', 'Ledgerline', 'Founder',
     'Fintech founder and ex-banker. Detail-oriented.',
     'Introduced by Lars Nielsen.', '2024-08-06', '2026-02-28', 3, 0.44, 0.88),
    (ws, 'Lucia Rossi', 'lucia.rossi@example.com', 'Verdigris', 'Climate Scientist',
     'Bridges climate science and product decisions.',
     'Met at a climate-tech hackathon.', '2025-01-22', '2026-05-27', 4, 0.50, 0.90),
    (ws, 'Nathan Cole', 'nathan.cole@example.com', 'Beacon', 'Engineering Manager',
     'EM who cares deeply about developer happiness.',
     'Met at a management book club.', '2023-10-03', '2026-03-08', 3, 0.42, 0.87),
    (ws, 'Sana Iqbal', 'sana.iqbal@example.com', 'Mosaic', 'Head of Product',
     'Product leader in the design-tools space.',
     'Introduced by Sofia Lindqvist.', '2024-06-30', '2026-06-12', 5, 0.60, 0.91),
    (ws, 'Elliot Grant', 'elliot.grant@example.com', 'Foundry VC', 'Associate',
     'Junior investor, hungry and genuinely helpful.',
     'Met at a demo day.', '2025-04-09', '2026-05-20', 3, 0.40, 0.87),
    (ws, 'Priya Venkatesh', 'priya.venkatesh@example.com', 'Aperture', 'Data Scientist',
     'Applied data scientist working on recommendation systems.',
     'Met at a data-science meetup.', '2024-02-17', '2025-10-30', 2, 0.30, 0.84),
    (ws, 'Jonas Weber', 'jonas.weber@example.com', 'Kettle', 'Founder',
     'Building infrastructure for real-time applications.',
     'Introduced by Kenji Tanaka.', '2024-12-01', '2026-04-14', 4, 0.50, 0.90),
    (ws, 'Amina Diallo', 'amina.diallo@example.com', 'Northstar Nonprofit', 'Executive Director',
     'Leads a youth-coding nonprofit.',
     'We serve on the Northstar board together.', '2022-09-12', '2026-05-03', 6, 0.66, 0.93),
    (ws, 'Theo Laurent', 'theo.laurent@example.com', 'Cirrus', 'Head of Marketing',
     'Content-driven marketer for developer tools.',
     'Met through a podcast interview.', '2023-08-24', '2025-12-30', 3, 0.40, 0.86),
    (ws, 'Rebecca Stone', 'rebecca.stone@example.com', 'Anchor', 'COO',
     'Operations leader scaling a marketplace.',
     'Met at an ops-leaders dinner.', '2024-03-15', '2026-03-22', 4, 0.50, 0.89),
    (ws, 'Hassan Malik', 'hassan.malik@example.com', 'Beacon Labs', 'Research Engineer',
     'Works on efficient inference for language models.',
     'Met at an ML conference.', '2025-05-16', '2026-06-08', 3, 0.42, 0.88),
    (ws, 'Clara Nguyen', 'clara.nguyen@example.com', 'Palette', 'Product Designer',
     'Systems-minded designer, ex-agency.',
     'Introduced by Rafael Santos.', '2023-12-07', '2026-02-15', 3, 0.44, 0.87),
    (ws, 'Victor Ivanov', 'victor.ivanov@example.com', 'Relay', 'Backend Engineer',
     'Distributed-systems engineer and active open-source contributor.',
     'Met via a GitHub project.', '2022-11-20', '2025-11-27', 3, 0.40, 0.86),
    (ws, 'Maya Goldberg', 'maya.goldberg@example.com', 'Sprout', 'Founder',
     'Consumer-social founder taking a community-first approach.',
     'Introduced by Nadia Haddad.', '2025-06-02', '2026-06-18', 3, 0.45, 0.88),
    (ws, 'Samuel Otieno', 'samuel.otieno@example.com', 'Ampere', 'Hardware Lead',
     'Builds hardware for off-grid energy systems.',
     'Met at a climate-hardware meetup.', '2024-10-19', '2026-04-07', 3, 0.44, 0.88),
    (ws, 'Julia Fernandes', 'julia.fernandes@example.com', 'Cascade', 'Head of BizDev',
     'Partnerships leader who connects ecosystems.',
     'Met at a partnerships summit.', '2023-03-11', '2025-10-05', 2, 0.30, 0.84),
    (ws, 'Isaac Bennett', 'isaac.bennett@example.com', 'Quill', 'Technical Writer',
     'Docs and developer-experience writer for API companies.',
     'Collaborated on open-source documentation.', '2022-07-08', '2026-01-12', 3, 0.40, 0.86),
    (ws, 'Lena Petrova', 'lena.petrova@example.com', 'Vertex Angels', 'Angel Investor',
     'Prolific angel who backs technical founders early.',
     'Met at an angel-syndicate event.', '2023-01-27', '2026-05-25', 5, 0.60, 0.91);

  ------------------------------------------------------------------
  -- Topics (9)
  ------------------------------------------------------------------
  INSERT INTO topic (workspace_id, name, description) VALUES
    (ws, 'AI agents', 'Autonomous LLM-driven systems and agent tooling.'),
    (ws, 'Fundraising', 'Startup fundraising, term sheets, and investor introductions.'),
    (ws, 'Design systems', 'Component libraries, design tokens, and UI consistency at scale.'),
    (ws, 'Climate tech', 'Energy, grid, and hardware technology for decarbonization.'),
    (ws, 'Developer tools', 'Build systems, developer productivity, and DX.'),
    (ws, 'Hiring', 'Recruiting, referrals, and building teams.'),
    (ws, 'Proptech', 'Real estate and property technology.'),
    (ws, 'Open source', 'Open-source projects, maintenance, and sustainability.'),
    (ws, 'Community building', 'Communities, events, and connecting people.');

  ------------------------------------------------------------------
  -- Person <-> Topic links (scalar subselects for FKs)
  ------------------------------------------------------------------
  INSERT INTO person_topic (workspace_id, person_id, topic_id, confidence, evidence_count, last_evidence_at, user_confirmed)
  VALUES
    -- Heroes
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='amara.osei@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='AI agents'), 0.92, 4, '2026-06-28', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='amara.osei@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Developer tools'), 0.60, 2, '2026-05-14', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='amara.osei@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Hiring'), 0.70, 2, '2026-06-28', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='diego.ramirez@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Climate tech'), 0.90, 3, '2026-06-10', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='diego.ramirez@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Fundraising'), 0.85, 3, '2026-06-10', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='sofia.lindqvist@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Design systems'), 0.95, 5, '2026-06-22', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='sofia.lindqvist@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Hiring'), 0.50, 1, '2026-06-22', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='kenji.tanaka@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Developer tools'), 0.90, 4, '2026-05-30', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='kenji.tanaka@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Open source'), 0.88, 3, '2026-05-30', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='kenji.tanaka@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Community building'), 0.50, 1, '2026-05-30', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='nadia.haddad@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Community building'), 0.95, 4, '2026-06-15', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='nadia.haddad@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Hiring'), 0.60, 2, '2026-05-25', false),
    -- Supporting network
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='marcus.bell@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Developer tools'), 0.70, 2, '2026-03-12', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='yuki.sato@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Design systems'), 0.40, 1, '2026-04-02', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='yuki.sato@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Community building'), 0.30, 1, '2026-04-02', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='olumide.adeyemi@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Climate tech'), 0.85, 2, '2026-05-18', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='olumide.adeyemi@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Fundraising'), 0.50, 1, '2026-05-18', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='hannah.cohen@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Hiring'), 0.70, 2, '2026-02-20', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='hannah.cohen@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Developer tools'), 0.40, 1, '2026-02-20', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='rafael.santos@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Design systems'), 0.60, 1, '2025-12-05', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='mei.chen@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='AI agents'), 0.75, 2, '2026-06-01', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='tomas.herrera@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Fundraising'), 0.30, 1, '2025-11-22', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='aisha.rahman@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Fundraising'), 0.50, 1, '2026-06-05', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='aisha.rahman@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Hiring'), 0.40, 1, '2026-06-05', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='lars.nielsen@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Fundraising'), 0.70, 2, '2025-10-14', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='lars.nielsen@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Proptech'), 0.30, 1, '2025-10-14', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='priyanka.nair@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Developer tools'), 0.80, 2, '2026-04-19', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='priyanka.nair@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Open source'), 0.50, 1, '2026-04-19', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='grace.okafor@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Climate tech'), 0.60, 1, '2026-03-30', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='daniel.park@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Developer tools'), 0.75, 2, '2026-05-11', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='fatima.alsayed@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Community building'), 0.50, 1, '2025-09-08', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='ben.whitfield@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Hiring'), 0.30, 1, '2025-12-19', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='ingrid.bergstrom@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Hiring'), 0.80, 2, '2026-04-25', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='carlos.mendoza@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='AI agents'), 0.40, 1, '2026-01-30', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='carlos.mendoza@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Design systems'), 0.30, 1, '2026-01-30', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='zoe.armstrong@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Design systems'), 0.40, 1, '2025-11-09', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='omar.farouk@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Fundraising'), 0.50, 1, '2026-02-28', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='omar.farouk@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Proptech'), 0.40, 1, '2026-02-28', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='lucia.rossi@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Climate tech'), 0.70, 2, '2026-05-27', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='nathan.cole@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Hiring'), 0.50, 1, '2026-03-08', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='nathan.cole@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Developer tools'), 0.40, 1, '2026-03-08', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='sana.iqbal@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Design systems'), 0.70, 2, '2026-06-12', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='elliot.grant@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Fundraising'), 0.50, 1, '2026-05-20', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='priya.venkatesh@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='AI agents'), 0.50, 1, '2025-10-30', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='jonas.weber@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Developer tools'), 0.70, 2, '2026-04-14', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='jonas.weber@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Open source'), 0.40, 1, '2026-04-14', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='amina.diallo@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Community building'), 0.80, 2, '2026-05-03', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='amina.diallo@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Fundraising'), 0.50, 1, '2026-05-03', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='theo.laurent@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Community building'), 0.40, 1, '2025-12-30', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='rebecca.stone@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Hiring'), 0.50, 1, '2026-03-22', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='hassan.malik@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='AI agents'), 0.70, 2, '2026-06-08', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='clara.nguyen@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Design systems'), 0.60, 1, '2026-02-15', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='victor.ivanov@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Open source'), 0.70, 2, '2025-11-27', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='victor.ivanov@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Developer tools'), 0.50, 1, '2025-11-27', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='maya.goldberg@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Community building'), 0.70, 2, '2026-06-18', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='samuel.otieno@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Climate tech'), 0.70, 2, '2026-04-07', true),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='julia.fernandes@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Community building'), 0.30, 1, '2025-10-05', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='isaac.bennett@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Open source'), 0.60, 1, '2026-01-12', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='isaac.bennett@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Developer tools'), 0.40, 1, '2026-01-12', false),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='lena.petrova@example.com'), (SELECT id FROM topic WHERE workspace_id=ws AND name='Fundraising'), 0.85, 3, '2026-05-25', true);

  ------------------------------------------------------------------
  -- Source items (25) -- each title unique
  ------------------------------------------------------------------
  INSERT INTO source_item (workspace_id, provider, source_type, title, body, author, participants, created_at_source) VALUES
    (ws, 'manual', 'email', 'Email: Loomwork agent demo follow-up',
     'Thanks for the demo notes -- the agent handling refunds end-to-end was the standout. Want to compare eval approaches next week? -- Amara',
     'amara.osei@example.com', '["amara.osei@example.com","me@example.com"]'::jsonb, '2026-05-14'),
    (ws, 'manual', 'meeting_note', 'Meeting notes: Coffee with Amara Osei',
     'Met Amara for coffee. She is scaling Loomwork to 15 people and struggling to hire senior ML engineers. Interested in our eval tooling.',
     'me', '["me@example.com","amara.osei@example.com"]'::jsonb, '2026-03-02'),
    (ws, 'manual', 'meeting_note', 'Call notes: Amara on hiring plan',
     'Quick call. Amara asked for intros to two ML engineers and is opening a small seed extension.',
     'me', '["me@example.com","amara.osei@example.com"]'::jsonb, '2026-06-28'),
    (ws, 'manual', 'meeting_note', 'Meeting notes: Meridian partner meeting',
     'Sat in on Meridian''s Monday partner meeting. Diego is doubling down on grid and battery software this year.',
     'me', '["me@example.com","diego.ramirez@example.com"]'::jsonb, '2026-01-19'),
    (ws, 'manual', 'email', 'Email: Re: intro to GridPositive',
     'Happy to intro you to Olumide at GridPositive -- he is exactly in our wheelhouse. Cc''ing you both. -- Diego',
     'diego.ramirez@example.com', '["diego.ramirez@example.com","me@example.com","olumide.adeyemi@example.com"]'::jsonb, '2025-02-10'),
    (ws, 'manual', 'meeting_note', 'Call notes: Diego on the raise',
     'Called Diego for fundraising advice. He suggested a tighter narrative and offered to preview the deck.',
     'me', '["me@example.com","diego.ramirez@example.com"]'::jsonb, '2026-06-10'),
    (ws, 'manual', 'meeting_note', 'Meeting notes: Design systems review with Sofia',
     'Reviewed Northwind''s new component library with Sofia. Impressive token architecture; she is rolling it out across three product teams.',
     'me', '["me@example.com","sofia.lindqvist@example.com"]'::jsonb, '2026-04-08'),
    (ws, 'manual', 'email', 'Email: Re: component library rollout',
     'The rollout is going well -- two teams migrated, one to go. I''ll send the migration guide you asked about. -- Sofia',
     'sofia.lindqvist@example.com', '["sofia.lindqvist@example.com","me@example.com"]'::jsonb, '2026-05-21'),
    (ws, 'manual', 'meeting_note', 'Call notes: Catch-up with Sofia',
     'Long catch-up. Sofia is thinking about hiring a design-systems lead and asked for candidate ideas.',
     'me', '["me@example.com","sofia.lindqvist@example.com"]'::jsonb, '2026-06-22'),
    (ws, 'manual', 'meeting_note', 'Meeting notes: Rustforge roadmap chat',
     'Kenji walked me through the Rustforge 2.0 roadmap. Focus on faster incremental builds and better plugin APIs.',
     'me', '["me@example.com","kenji.tanaka@example.com"]'::jsonb, '2026-02-24'),
    (ws, 'manual', 'email', 'Email: Re: build tool RFC',
     'Appreciate the RFC feedback. I''ll fold in your notes on the caching layer before the next release. -- Kenji',
     'kenji.tanaka@example.com', '["kenji.tanaka@example.com","me@example.com"]'::jsonb, '2026-04-30'),
    (ws, 'manual', 'meeting_note', 'Call notes: OSS maintainers sync',
     'Maintainers call. Kenji is worried about sustainability and wants to set up a funding model for the project.',
     'me', '["me@example.com","kenji.tanaka@example.com"]'::jsonb, '2026-05-30'),
    (ws, 'manual', 'meeting_note', 'Meeting notes: Assembly community strategy',
     'Nadia shared Assembly''s community playbook. Small curated dinners beat big events every time.',
     'me', '["me@example.com","nadia.haddad@example.com"]'::jsonb, '2026-03-18'),
    (ws, 'manual', 'email', 'Email: Re: operator dinner invite',
     'You''re on the list for the June dinner -- seating eight operators, theme is scaling past 50 people. -- Nadia',
     'nadia.haddad@example.com', '["nadia.haddad@example.com","me@example.com"]'::jsonb, '2026-05-25'),
    (ws, 'manual', 'meeting_note', 'Message thread: Nadia intros',
     'DM thread. Nadia offered to introduce me to Aisha and Maya -- both building community-first products.',
     'me', '["me@example.com","nadia.haddad@example.com"]'::jsonb, '2026-06-15'),
    (ws, 'manual', 'meeting_note', 'Meeting notes: Battery software deep-dive',
     'Deep-dive with Olumide on GridPositive''s battery-dispatch software. Strong technical moat.',
     'me', '["me@example.com","olumide.adeyemi@example.com"]'::jsonb, '2026-05-18'),
    (ws, 'manual', 'meeting_note', 'Call notes: Kindred Health intro',
     'Intro call with Aisha. Kindred Health is building patient navigation for small clinics and is looking for a technical advisor.',
     'me', '["me@example.com","aisha.rahman@example.com"]'::jsonb, '2026-06-05'),
    (ws, 'manual', 'meeting_note', 'Meeting notes: Catch-up with Priyanka',
     'Caught up with Priyanka. She is the founding engineer at Loopback and loving the developer-tools problem space.',
     'me', '["me@example.com","priyanka.nair@example.com"]'::jsonb, '2026-04-19'),
    (ws, 'manual', 'email', 'Email: Re: dev productivity beta',
     'The beta is live -- would love your feedback on the keyboard-first workflow. -- Daniel',
     'daniel.park@example.com', '["daniel.park@example.com","me@example.com"]'::jsonb, '2026-05-11'),
    (ws, 'manual', 'meeting_note', 'Meeting notes: Northstar board meeting',
     'Quarterly Northstar board meeting. Amina reported strong program growth and a funding gap for next year.',
     'me', '["me@example.com","amina.diallo@example.com"]'::jsonb, '2026-05-03'),
    (ws, 'manual', 'email', 'Email: Re: product roadmap swap',
     'Swapping roadmaps was useful -- our design-tools bets overlap a lot. Let''s do this quarterly. -- Sana',
     'sana.iqbal@example.com', '["sana.iqbal@example.com","me@example.com"]'::jsonb, '2026-06-12'),
    (ws, 'manual', 'meeting_note', 'Call notes: Kettle infra intro',
     'Kenji introduced me to Jonas. Kettle is building real-time infra and he wants early design partners.',
     'me', '["me@example.com","jonas.weber@example.com"]'::jsonb, '2026-04-14'),
    (ws, 'manual', 'meeting_note', 'Meeting notes: Data pipeline chat with Marcus',
     'Marcus walked through Cadence''s data-pipeline architecture and pain points with schema drift.',
     'me', '["me@example.com","marcus.bell@example.com"]'::jsonb, '2026-03-12'),
    (ws, 'manual', 'email', 'Email: Re: angel round for a friend',
     'Send me the deck -- if the founder is technical and coachable I''ll take a look. -- Lena',
     'lena.petrova@example.com', '["lena.petrova@example.com","me@example.com"]'::jsonb, '2026-05-25'),
    (ws, 'manual', 'meeting_note', 'Meeting notes: Sprout community launch',
     'Maya shared Sprout''s launch plan -- community-first and invite-only beta. Smart wedge.',
     'me', '["me@example.com","maya.goldberg@example.com"]'::jsonb, '2026-06-18');

  ------------------------------------------------------------------
  -- Interactions (25) -- each title unique; FK via source_item title
  ------------------------------------------------------------------
  INSERT INTO interaction (workspace_id, source_item_id, interaction_type, title, summary, body, occurred_at, topics) VALUES
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Email: Loomwork agent demo follow-up'), 'email', 'Follow-up on Loomwork agent demo',
     'Amara shared demo notes and wants to compare evaluation approaches for agent reliability.',
     'Thanks for the demo notes -- the agent handling refunds end-to-end was the standout.', '2026-05-14', '["AI agents","Developer tools"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Coffee with Amara Osei'), 'meeting', 'Coffee with Amara Osei',
     'Discussed scaling Loomwork, hiring senior ML engineers, and agent evaluation.',
     'She is scaling Loomwork to 15 people and struggling to hire senior ML engineers.', '2026-03-02', '["AI agents","Hiring"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Call notes: Amara on hiring plan'), 'call', 'Call with Amara about hiring and seed extension',
     'Amara wants ML engineer intros and is raising a small seed extension.',
     'Amara asked for intros to two ML engineers and is opening a small seed extension.', '2026-06-28', '["Hiring","Fundraising"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Meridian partner meeting'), 'meeting', 'Meridian Ventures partner meeting',
     'Diego outlined Meridian''s climate thesis, focused on grid and battery software.',
     'Diego is doubling down on grid and battery software this year.', '2026-01-19', '["Climate tech","Fundraising"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Email: Re: intro to GridPositive'), 'email', 'Diego intro to GridPositive',
     'Diego offered to introduce me to Olumide at GridPositive.',
     'Happy to intro you to Olumide at GridPositive -- he is exactly in our wheelhouse.', '2025-02-10', '["Climate tech"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Call notes: Diego on the raise'), 'call', 'Fundraising advice call with Diego',
     'Diego gave feedback on the fundraising narrative and offered to review the deck.',
     'He suggested a tighter narrative and offered to preview the deck.', '2026-06-10', '["Fundraising"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Design systems review with Sofia'), 'meeting', 'Design systems review with Sofia',
     'Walked through Northwind''s component library and its token architecture rollout.',
     'Impressive token architecture; she is rolling it out across three product teams.', '2026-04-08', '["Design systems"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Email: Re: component library rollout'), 'email', 'Component library rollout update',
     'Sofia shared progress migrating teams onto the new design system.',
     'The rollout is going well -- two teams migrated, one to go.', '2026-05-21', '["Design systems"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Call notes: Catch-up with Sofia'), 'call', 'Catch-up call with Sofia',
     'Sofia is hiring a design-systems lead and wants candidate referrals.',
     'Sofia is thinking about hiring a design-systems lead and asked for candidate ideas.', '2026-06-22', '["Design systems","Hiring"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Rustforge roadmap chat'), 'meeting', 'Rustforge roadmap chat',
     'Kenji shared the Rustforge 2.0 roadmap centered on incremental builds and plugin APIs.',
     'Focus on faster incremental builds and better plugin APIs.', '2026-02-24', '["Developer tools","Open source"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Email: Re: build tool RFC'), 'email', 'Build tool RFC feedback',
     'Exchanged feedback on the Rustforge caching-layer RFC.',
     'I''ll fold in your notes on the caching layer before the next release.', '2026-04-30', '["Developer tools","Open source"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Call notes: OSS maintainers sync'), 'call', 'Open-source maintainers call with Kenji',
     'Discussed maintainer burnout and funding models for the Rustforge project.',
     'Kenji wants to set up a funding model for the project.', '2026-05-30', '["Open source","Community building"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Assembly community strategy'), 'meeting', 'Assembly community strategy session',
     'Nadia walked through Assembly''s playbook for curated operator dinners.',
     'Small curated dinners beat big events every time.', '2026-03-18', '["Community building"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Email: Re: operator dinner invite'), 'email', 'Operator dinner invitation from Nadia',
     'Nadia invited me to a curated operator dinner on scaling past 50 people.',
     'You''re on the list for the June dinner -- seating eight operators.', '2026-05-25', '["Community building","Hiring"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Message thread: Nadia intros'), 'message', 'Intro thread with Nadia',
     'Nadia offered warm intros to Aisha and Maya.',
     'Nadia offered to introduce me to Aisha and Maya.', '2026-06-15', '["Community building"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Battery software deep-dive'), 'meeting', 'Battery software deep-dive with Olumide',
     'Olumide explained GridPositive''s battery-dispatch software and its technical moat.',
     'Deep-dive on GridPositive''s battery-dispatch software.', '2026-05-18', '["Climate tech"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Call notes: Kindred Health intro'), 'call', 'Kindred Health intro call',
     'Aisha introduced Kindred Health and is seeking a technical advisor.',
     'Kindred Health is building patient navigation for small clinics.', '2026-06-05', '["Hiring"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Catch-up with Priyanka'), 'meeting', 'Catch-up with Priyanka',
     'Priyanka shared her work as founding engineer at Loopback.',
     'She is the founding engineer at Loopback and loving the developer-tools space.', '2026-04-19', '["Developer tools"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Email: Re: dev productivity beta'), 'email', 'Dev productivity beta feedback request',
     'Daniel invited me to test Stacks'' keyboard-first productivity beta.',
     'Would love your feedback on the keyboard-first workflow.', '2026-05-11', '["Developer tools"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Northstar board meeting'), 'meeting', 'Northstar Nonprofit board meeting',
     'Amina reported program growth and flagged a funding gap for next year.',
     'Amina reported strong program growth and a funding gap for next year.', '2026-05-03', '["Community building","Fundraising"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Email: Re: product roadmap swap'), 'email', 'Product roadmap swap with Sana',
     'Sana and I compared product roadmaps in the design-tools space.',
     'Our design-tools bets overlap a lot. Let''s do this quarterly.', '2026-06-12', '["Design systems"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Call notes: Kettle infra intro'), 'call', 'Kettle infrastructure intro call',
     'Jonas introduced Kettle''s real-time infra and is looking for design partners.',
     'Kettle is building real-time infra and he wants early design partners.', '2026-04-14', '["Developer tools"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Data pipeline chat with Marcus'), 'meeting', 'Data pipeline chat with Marcus',
     'Marcus described Cadence''s pipeline architecture and schema-drift challenges.',
     'Marcus walked through Cadence''s data-pipeline architecture.', '2026-03-12', '["Developer tools"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Email: Re: angel round for a friend'), 'email', 'Angel round intro to Lena',
     'Lena offered to review a founder''s deck for a potential angel check.',
     'Send me the deck -- if the founder is technical and coachable I''ll take a look.', '2026-05-25', '["Fundraising"]'::jsonb),
    (ws, (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Sprout community launch'), 'meeting', 'Sprout community launch review',
     'Maya walked through Sprout''s invite-only, community-first launch plan.',
     'Community-first and invite-only beta. Smart wedge.', '2026-06-18', '["Community building"]'::jsonb);

  ------------------------------------------------------------------
  -- Interaction participants (FK via interaction title + person email)
  ------------------------------------------------------------------
  INSERT INTO interaction_participant (workspace_id, interaction_id, person_id, role) VALUES
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Follow-up on Loomwork agent demo'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='amara.osei@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Coffee with Amara Osei'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='amara.osei@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Call with Amara about hiring and seed extension'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='amara.osei@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Meridian Ventures partner meeting'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='diego.ramirez@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Diego intro to GridPositive'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='diego.ramirez@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Diego intro to GridPositive'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='olumide.adeyemi@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Fundraising advice call with Diego'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='diego.ramirez@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Design systems review with Sofia'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='sofia.lindqvist@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Component library rollout update'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='sofia.lindqvist@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Catch-up call with Sofia'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='sofia.lindqvist@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Rustforge roadmap chat'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='kenji.tanaka@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Build tool RFC feedback'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='kenji.tanaka@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Open-source maintainers call with Kenji'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='kenji.tanaka@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Assembly community strategy session'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='nadia.haddad@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Operator dinner invitation from Nadia'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='nadia.haddad@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Intro thread with Nadia'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='nadia.haddad@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Battery software deep-dive with Olumide'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='olumide.adeyemi@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Kindred Health intro call'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='aisha.rahman@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Catch-up with Priyanka'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='priyanka.nair@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Dev productivity beta feedback request'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='daniel.park@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Northstar Nonprofit board meeting'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='amina.diallo@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Product roadmap swap with Sana'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='sana.iqbal@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Kettle infrastructure intro call'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='jonas.weber@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Data pipeline chat with Marcus'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='marcus.bell@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Angel round intro to Lena'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='lena.petrova@example.com'), 'participant'),
    (ws, (SELECT id FROM interaction WHERE workspace_id=ws AND title='Sprout community launch review'), (SELECT id FROM person WHERE workspace_id=ws AND primary_email='maya.goldberg@example.com'), 'participant');

  ------------------------------------------------------------------
  -- Evidence (8 person_topic claims)
  ------------------------------------------------------------------
  INSERT INTO evidence (workspace_id, claim_type, claim_id, source_item_id, interaction_id, quote, summary) VALUES
    (ws, 'person_topic',
     (SELECT id FROM person_topic WHERE workspace_id=ws AND person_id=(SELECT id FROM person WHERE workspace_id=ws AND primary_email='amara.osei@example.com') AND topic_id=(SELECT id FROM topic WHERE workspace_id=ws AND name='AI agents')),
     (SELECT id FROM source_item WHERE workspace_id=ws AND title='Email: Loomwork agent demo follow-up'),
     (SELECT id FROM interaction WHERE workspace_id=ws AND title='Follow-up on Loomwork agent demo'),
     'the agent handling refunds end-to-end was the standout', 'Amara is building production agents at Loomwork.'),
    (ws, 'person_topic',
     (SELECT id FROM person_topic WHERE workspace_id=ws AND person_id=(SELECT id FROM person WHERE workspace_id=ws AND primary_email='amara.osei@example.com') AND topic_id=(SELECT id FROM topic WHERE workspace_id=ws AND name='Hiring')),
     (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Coffee with Amara Osei'),
     (SELECT id FROM interaction WHERE workspace_id=ws AND title='Coffee with Amara Osei'),
     'struggling to hire senior ML engineers', 'Amara is actively hiring ML engineers.'),
    (ws, 'person_topic',
     (SELECT id FROM person_topic WHERE workspace_id=ws AND person_id=(SELECT id FROM person WHERE workspace_id=ws AND primary_email='diego.ramirez@example.com') AND topic_id=(SELECT id FROM topic WHERE workspace_id=ws AND name='Climate tech')),
     (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Meridian partner meeting'),
     (SELECT id FROM interaction WHERE workspace_id=ws AND title='Meridian Ventures partner meeting'),
     'doubling down on grid and battery software this year', 'Diego''s investment focus is climate and grid.'),
    (ws, 'person_topic',
     (SELECT id FROM person_topic WHERE workspace_id=ws AND person_id=(SELECT id FROM person WHERE workspace_id=ws AND primary_email='diego.ramirez@example.com') AND topic_id=(SELECT id FROM topic WHERE workspace_id=ws AND name='Fundraising')),
     (SELECT id FROM source_item WHERE workspace_id=ws AND title='Call notes: Diego on the raise'),
     (SELECT id FROM interaction WHERE workspace_id=ws AND title='Fundraising advice call with Diego'),
     'suggested a tighter narrative and offered to preview the deck', 'Diego actively advises on fundraising.'),
    (ws, 'person_topic',
     (SELECT id FROM person_topic WHERE workspace_id=ws AND person_id=(SELECT id FROM person WHERE workspace_id=ws AND primary_email='sofia.lindqvist@example.com') AND topic_id=(SELECT id FROM topic WHERE workspace_id=ws AND name='Design systems')),
     (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Design systems review with Sofia'),
     (SELECT id FROM interaction WHERE workspace_id=ws AND title='Design systems review with Sofia'),
     'Impressive token architecture; she is rolling it out across three product teams', 'Sofia leads design-systems work at Northwind.'),
    (ws, 'person_topic',
     (SELECT id FROM person_topic WHERE workspace_id=ws AND person_id=(SELECT id FROM person WHERE workspace_id=ws AND primary_email='kenji.tanaka@example.com') AND topic_id=(SELECT id FROM topic WHERE workspace_id=ws AND name='Developer tools')),
     (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Rustforge roadmap chat'),
     (SELECT id FROM interaction WHERE workspace_id=ws AND title='Rustforge roadmap chat'),
     'Focus on faster incremental builds and better plugin APIs', 'Kenji drives the developer-tooling roadmap at Rustforge.'),
    (ws, 'person_topic',
     (SELECT id FROM person_topic WHERE workspace_id=ws AND person_id=(SELECT id FROM person WHERE workspace_id=ws AND primary_email='kenji.tanaka@example.com') AND topic_id=(SELECT id FROM topic WHERE workspace_id=ws AND name='Open source')),
     (SELECT id FROM source_item WHERE workspace_id=ws AND title='Call notes: OSS maintainers sync'),
     (SELECT id FROM interaction WHERE workspace_id=ws AND title='Open-source maintainers call with Kenji'),
     'wants to set up a funding model for the project', 'Kenji is an active open-source maintainer.'),
    (ws, 'person_topic',
     (SELECT id FROM person_topic WHERE workspace_id=ws AND person_id=(SELECT id FROM person WHERE workspace_id=ws AND primary_email='nadia.haddad@example.com') AND topic_id=(SELECT id FROM topic WHERE workspace_id=ws AND name='Community building')),
     (SELECT id FROM source_item WHERE workspace_id=ws AND title='Meeting notes: Assembly community strategy'),
     (SELECT id FROM interaction WHERE workspace_id=ws AND title='Assembly community strategy session'),
     'Small curated dinners beat big events every time', 'Nadia is a community-building expert.');

  ------------------------------------------------------------------
  -- Commitments (15) -- open loops, mix of statuses/due dates
  ------------------------------------------------------------------
  INSERT INTO commitment (workspace_id, person_id, interaction_id, description, status, due_date) VALUES
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='amara.osei@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Call with Amara about hiring and seed extension'), 'Intro Amara to two senior ML engineers I rate highly.', 'open', '2026-07-15'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='amara.osei@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Follow-up on Loomwork agent demo'), 'Send Amara our agent-evaluation tooling overview.', 'done', NULL),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='diego.ramirez@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Fundraising advice call with Diego'), 'Send Diego the updated fundraising deck for review.', 'open', '2026-06-30'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='diego.ramirez@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Meridian Ventures partner meeting'), 'Send Diego the climate portfolio market memo.', 'done', NULL),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='sofia.lindqvist@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Catch-up call with Sofia'), 'Send Sofia three design-systems lead candidates.', 'open', '2026-07-10'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='sofia.lindqvist@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Component library rollout update'), 'Follow up on the Northwind migration guide Sofia promised.', 'open', NULL),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='kenji.tanaka@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Build tool RFC feedback'), 'Review Kenji''s caching-layer RFC changes before the release.', 'open', NULL),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='kenji.tanaka@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Open-source maintainers call with Kenji'), 'Draft an open-source funding proposal to share with Kenji.', 'open', '2026-07-20'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='nadia.haddad@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Operator dinner invitation from Nadia'), 'Confirm attendance for Nadia''s June operator dinner.', 'done', NULL),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='nadia.haddad@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Intro thread with Nadia'), 'Follow up with Nadia on the Aisha and Maya intros.', 'open', NULL),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='olumide.adeyemi@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Battery software deep-dive with Olumide'), 'Send Olumide the battery-software market notes.', 'open', '2026-06-15'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='aisha.rahman@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Kindred Health intro call'), 'Decide whether to take the Kindred Health technical advisor role.', 'open', NULL),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='daniel.park@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Dev productivity beta feedback request'), 'Send Daniel feedback on the Stacks keyboard-first beta.', 'done', NULL),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='amina.diallo@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Northstar Nonprofit board meeting'), 'Connect Northstar with two potential funders for next year.', 'open', '2026-08-01'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='lena.petrova@example.com'), (SELECT id FROM interaction WHERE workspace_id=ws AND title='Angel round intro to Lena'), 'Forward the founder''s deck to Lena for an angel look.', 'open', '2026-06-01');

  ------------------------------------------------------------------
  -- Notes (~12 people)
  ------------------------------------------------------------------
  INSERT INTO note (workspace_id, person_id, body) VALUES
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='amara.osei@example.com'), 'Moves fast -- send bullet points, not essays. Training for a marathon this fall.'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='diego.ramirez@example.com'), 'Coffee, not lunch. Two young kids, so avoid early mornings. Big on tennis.'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='sofia.lindqvist@example.com'), 'Ex-colleague from the agency. Vegetarian. Prefers Figma comments to meetings.'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='kenji.tanaka@example.com'), 'Based in Kyoto -- mind the time zone. Deeply values async. Ask about his woodworking.'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='nadia.haddad@example.com'), 'A connector -- always ask who she thinks I should meet next. Gluten-free.'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='olumide.adeyemi@example.com'), 'Introduced by Diego. Very technical; skip the fluff. Based in Nairobi.'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='aisha.rahman@example.com'), 'Warm and mission-driven. Has a newborn -- keep asks light this year.'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='priyanka.nair@example.com'), 'Old teammate and good friend. Loves board games. Dog named Pixel.'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='amina.diallo@example.com'), 'We serve on the Northstar board together. Prefers phone calls to email.'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='daniel.park@example.com'), 'Solo founder -- protective of his time. Coffee snob; recommend a good roaster.'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='marcus.bell@example.com'), 'Dry humor -- do not mistake it for disinterest. Keen cyclist.'),
    (ws, (SELECT id FROM person WHERE workspace_id=ws AND primary_email='lena.petrova@example.com'), 'Angel investor who decides fast. Send decks, not intros to intros.');

END $$;
